Add support for ROOT & intermediary CA certificates stored on Tokens: create a new CA inside a Token, load existing CA into a Token, sign CSR files with a CA Token, create & sign new client server certificates with a CA Token

diff --git a/easy-rsa/2.0/pkitool b/easy-rsa/2.0/pkitool
--- a/easy-rsa/2.0/pkitool
+++ b/easy-rsa/2.0/pkitool
@@ -72,6 +72,7 @@ usage()
  	echo "      lib    : PKCS#11 library"
     echo "      slot   : PKCS#11 slot"
     echo "      id     : PKCS#11 object id (hex string)"
+	echo "      options: [client|--server|--inter|--sign|--pkcs11]"
 	echo "  --pkcs11   : generate certificate on PKCS#11 token"
     echo "      lib    : PKCS#11 library"
     echo "      slot   : PKCS#11 slot"
@@ -116,8 +117,11 @@ usage()
     echo "  $PROGNAME --pkcs12 client3  -> Build \"client3\" certificate/key in PKCS#12 format"
     echo "  $PROGNAME --csr client4     -> Build \"client4\" CSR to be signed by another CA"
     echo "  $PROGNAME --sign client4    -> Sign \"client4\" CSR"
-	echo "  $PROGNAME --pkcs11-ca 1 01 --sign client5"    
-	echo "                              -> Sign \"client5\" CSR with a CA stored on a PKCS#11 token"
+	echo "  $PROGNAME --pkcs11-use-tokenca  /usr/lib/pkcs11/lib1 1 010203 --sign client4"
+	echo "                              -> Sign \"client4\" CSR with the CA in the token slot:1 id:010203"
+	echo "  $PROGNAME --pkcs11-use-tokenca  /usr/lib/pkcs11/lib1 1 010203 \"client5\" "   
+	echo "                              -> Build \"client5\" certificate/key and sign it with"
+	echo "                                 the CA stored on the PKCS#11 token slot:1 id:010203"
     echo "  $PROGNAME --inter interca   -> Build an intermediate key-signing certificate/key"
     echo "                               Also see ./inherit-inter script."
     echo "  $PROGNAME --pkcs11 /usr/lib/pkcs11/lib1 0 010203 \"client5 id\" client5"
@@ -395,13 +399,18 @@ if [ -d "$KEY_DIR" ] && [ "$KEY_CONFIG" ]; then
 		echo "Try $PROGNAME --initca or --pkcs11-initca to build a root certificate/key."
 		exit 1
 	    fi
+	  if [ ! -r "$CA.crt" ] && [ $USE_PKCS11_CA -eq 1 ] ; then
+		echo "$PROGNAME: Need a readable $CA.crt in $KEY_DIR"
+		echo "Try $PROGNAME --initca or --pkcs11-initca to build a root certificate/key."
+		exit 1
+	    fi	
 	fi
 
 	# Generate key for PKCS#11 token
 	PKCS11_ARGS=
 	if [ $DO_P11 -eq 1 ]; then
 	        stty -echo
-	        printf "User PIN: "
+			printf "Connect your client/server Token with slot:$PKCS11_SLOT\nUser PIN:"
 	        read -r PKCS11_PIN
 	        stty echo
 		export PKCS11_PIN
@@ -428,10 +437,10 @@ if [ -d "$KEY_DIR" ] && [ "$KEY_CONFIG" ]; then
 		DO_CA="0"	
   	  fi
 
-# Function for signing a certificate with a CA stored on a hardware Token
+# Function for signing a certificate with a CA stored on a hardware Token. Use it recursive in case the pin fails
 signWithCAToken(){
 	  	stty -echo
-	    printf "Enter your CA Token in slot:$CA_PKCS11_SLOT\nCA Token user PIN: "
+	    printf "Connect your ** CA Token ** with slot:$CA_PKCS11_SLOT\n*CA Token* user PIN: "
 	    read -r PKCS11_PIN
 	    stty echo
 		export PKCS11_PIN	
@@ -439,7 +448,7 @@ signWithCAToken(){
 		KEY=slot_$CA_PKCS11_SLOT-id_$CA_PKCS11_ID
 		CA_PKCS11_ARGS="-engine pkcs11 -keyfile $KEY -keyform engine"
 		$OPENSSL ca $CA_PKCS11_ARGS $BATCH -days $KEY_EXPIRE -out "$FN.crt" \
-		 -in "$FN.csr" $CA_EXT -config "$KEY_CONFIG"
+		 -in "$FN.csr" $CA_EXT -config "$KEY_CONFIG" || signWithCAToken
 }
 
         # Build cert/key
@@ -463,14 +472,27 @@ signWithCAToken(){
 	    $PKCS15INIT  --store-certificate "$CA.der" --authority --auth-id 01 --id "$PKCS11_ID" \
 		             --pin "$PKCS11_PIN" --format der --label  "$PKCS11_LABEL" || exit 1
 	fi
-	
+
+# Function for loading a certificate into a PKCS#11 token. Use it recursive in case the pin fails	
+loadCertificateIntoToken(){
+	    if [ $USE_PKCS11_CA -eq 1 ]; then
+			stty -echo
+	    	printf "Enter your client/server Token in slot:$PKCS11_SLOT, and it will be loaded with the signed certificate: \"$FN.crt\" \nUser PIN: "
+	    	read -r PKCS11_PIN
+	    	stty echo
+			export PKCS11_PIN	
+		fi
+		echo "Loading certificate into Token....."
+		$OPENSSL x509 -in "$FN.crt" -inform PEM -out "$FN.der" -outform DER && \
+		  $PKCS11TOOL --module "$PKCS11_MODULE_PATH" --write-object "$FN.der" --type cert \
+			--login --pin "$PKCS11_PIN" \
+			--slot "$PKCS11_SLOT" --id "$PKCS11_ID" --label "$PKCS11_LABEL" || (USE_PKCS11_CA="1" && loadCertificateIntoToken) 
+		[ -e "$FN.der" ]; rm -f "$FN.der"	
+	}	
+
 	# Load certificate into PKCS#11 token
 	if [ $DO_P11 -eq 1 ]; then
-		$OPENSSL x509 -in "$FN.crt" -inform PEM -out "$FN.crt.der" -outform DER && \
-		  $PKCS11TOOL --module "$PKCS11_MODULE_PATH" --write-object "$FN.crt.der" --type cert \
-			--login --pin "$PKCS11_PIN" \
-			--slot "$PKCS11_SLOT" --id "$PKCS11_ID" --label "$PKCS11_LABEL" 
-		[ -e "$FN.crt.der" ]; rm "$FN.crt.der"
+		loadCertificateIntoToken
 	fi
 
     fi
