Fully enable install_data_to_pki()
* init-pki
  Always use install_data_to_pki() - New Default

* setup_vars()
  Always use install_data_to_pki() - New Default

Signed-off-by: Richard T Bonhomme <tincantech@protonmail.com>

diff --git a/easyrsa3/easyrsa b/easyrsa3/easyrsa
--- a/easyrsa3/easyrsa
+++ b/easyrsa3/easyrsa
@@ -559,11 +559,15 @@ and initialize a fresh PKI here."
 		mkdir -p "$EASYRSA_PKI/$i" || die "Failed to create PKI file structure (permissions?)"
 	done
 
-	# Create $EASYRSA_SAFE_CONF ($OPENSSL_CONF) prevents bogus warnings (especially useful on win32)
-	if [ ! -f "$EASYRSA_SSL_CONF" ] && [ -f "$EASYRSA/openssl-easyrsa.cnf" ];
-	then
-		cp "$EASYRSA/openssl-easyrsa.cnf" "$EASYRSA_SSL_CONF"
-		easyrsa_openssl makesafeconf
+	# Install data-files into ALL new PKIs
+	install_data_to_pki || die "Failed to install required data-files to PKI."
+
+	# Verify that $EASYRSA_SAFE_CONF exists ($OPENSSL_CONF)
+	# Prevents bogus warnings (especially useful on win32)
+	if [ -n "$EASYRSA_SAFE_CONF" ] && [ -e "$EASYRSA_SAFE_CONF" ]; then
+		: # ok
+	else
+		die "init-pki failed to create safe SSL conf: $EASYRSA_SAFE_CONF"
 	fi
 
 	notice "\
@@ -787,9 +791,8 @@ install_data_to_pki () {
 		fi
 	fi
 
-	# Check or error
-	easyrsa_openssl makesafeconf || \
-		die "Failed to make safe SSL config file in PKI."
+	# Complete or error
+	[ -e "$EASYRSA_PKI_SAFE_CONF" ] || easyrsa_openssl makesafeconf
 } # => install_data_to_pki ()
 
 # Copy the source to the PKI
@@ -2089,10 +2092,12 @@ Note: using Easy-RSA configuration from: $vars"
 			else
 
 			#TODO: This should be removed.  Not really suitable for packaging.
-			set_var EASYRSA_EXT_DIR		"$EASYRSA/x509-types"
+			#set_var EASYRSA_EXT_DIR		"$EASYRSA/x509-types"
 
+			# Hard break from 'old' Easy-RSA, see obsolete comment above.
 				# Install data-files into ALL PKIs
-				#install_data_to_pki || die "Failed to install new required data-dir to PKI."
+				install_data_to_pki || die "Failed to install new required data-dir to PKI."
+				set_var EASYRSA_EXT_DIR		"$EASYRSA_PKI/x509-types"
 			fi
 
 			# Setting EasyRSA specific OPENSSL_CONF to sanatized safe conf
@@ -2100,8 +2105,10 @@ Note: using Easy-RSA configuration from: $vars"
 				export OPENSSL_CONF="$EASYRSA_SAFE_CONF"
 			else
 				# Install data-files into ALL PKIs
-				#install_data_to_pki || die "Failed to install new required data-files to PKI."
-				: # ok
+				install_data_to_pki || die "Failed to install new required data-files to PKI."
+				# EASYRSA_PKI_SAFE_CONF is output by
+				# 'install_data_to_pki()' via 'easyrsa_openssl() makesafeconf'
+				export OPENSSL_CONF="$EASYRSA_PKI_SAFE_CONF"
 			fi
 
 			# Upgrade to 306: Create $EASYRSA_SSL_CONF if it does not exist
