Rename function build_self_sign() to self_sign()
Signed-off-by: Richard T Bonhomme <tincantech@protonmail.com>

diff --git a/easyrsa3/easyrsa b/easyrsa3/easyrsa
--- a/easyrsa3/easyrsa
+++ b/easyrsa3/easyrsa
@@ -1864,7 +1864,7 @@ CA creation complete. Your new CA certificate is at:
 } # => build_ca()
 
 # Build self signed key pair
-build_self_sign() {
+self_sign() {
 	# Define x509 type
 	case "$1" in
 		server)
@@ -1874,7 +1874,7 @@ build_self_sign() {
 			selfsign_eku=clientAuth
 			;;
 		*)
-			die "build_self_sign: Unknown EKU '$1'"
+			die "self_sign: Unknown EKU '$1'"
 	esac
 	shift
 
@@ -1959,7 +1959,7 @@ self-sign: Use ALGO/CURVE to $EASYRSA_ALGO/$EASYRSA_CURVE"
 	# Assign tmp-file for config
 	adjusted_ssl_cnf_tmp=""
 	easyrsa_mktemp adjusted_ssl_cnf_tmp || \
-		die "build_self_sign - easyrsa_mktemp adjusted_ssl_cnf_tmp"
+		die "self_sign - easyrsa_mktemp adjusted_ssl_cnf_tmp"
 
 	# Assign awkscript to insert EASYRSA_EXTRA_EXTS
 	# shellcheck disable=SC2016 # No expand '' - build_ca()
@@ -2001,7 +2001,7 @@ self-sign: Use ALGO/CURVE to $EASYRSA_ALGO/$EASYRSA_CURVE"
 	} | awk "$awkscript" "$EASYRSA_SSL_CONF" \
 			> "$adjusted_ssl_cnf_tmp" || \
 				die "Copying X509_TYPES to config file failed"
-	verbose "build_self_sign: insert x509 and extensions OK"
+	verbose "self_sign: insert x509 and extensions OK"
 
 	# Use this new SSL config for the rest of this function
 	EASYRSA_SSL_CONF="$adjusted_ssl_cnf_tmp"
@@ -2009,22 +2009,22 @@ self-sign: Use ALGO/CURVE to $EASYRSA_ALGO/$EASYRSA_CURVE"
 	# temp-file for params-file
 	selfsign_params_file=""
 	easyrsa_mktemp selfsign_params_file || \
-		die "build_self_sign - easyrsa_mktemp selfsign_params_file"
+		die "self_sign - easyrsa_mktemp selfsign_params_file"
 
 	# params-file
 	"$EASYRSA_OPENSSL" ecparam \
 		-name "$EASYRSA_CURVE" \
 		-out "$selfsign_params_file" || \
-			die "build_self_sign - params-file failed"
+			die "self_sign - params-file failed"
 
 	# Create temp-files for output
 	tmp_key_out=""
 	easyrsa_mktemp tmp_key_out || \
-		die "build_self_sign - easyrsa_mktemp tmp_key_out"
+		die "self_sign - easyrsa_mktemp tmp_key_out"
 
 	tmp_crt_out=""
 	easyrsa_mktemp tmp_crt_out || \
-		die "build_self_sign - easyrsa_mktemp tmp_crt_out"
+		die "self_sign - easyrsa_mktemp tmp_crt_out"
 
 	# create self-signed key pair
 	easyrsa_openssl req -x509 -utf8 -sha256 -text \
@@ -2051,7 +2051,7 @@ self-sign: Use ALGO/CURVE to $EASYRSA_ALGO/$EASYRSA_CURVE"
 	crt_fingerprint="$(
 		"$EASYRSA_OPENSSL" x509 -in "$crt_out" -noout \
 			-sha256 -fingerprint
-	)" || die "build_self_sign - Failed -fingerprint"
+	)" || die "self_sign - Failed -fingerprint"
 
 	# strip fingerprint prefix
 	crt_fingerprint="${crt_fingerprint#*=}"
@@ -2076,7 +2076,7 @@ Inline file created:
 INCOMPLETE Inline file created:
 * $inline_out"
 	fi
-} # => build_self_sign()
+} # => self_sign()
 
 # gen-dh backend:
 gen_dh() {
@@ -2839,7 +2839,7 @@ inline_creds() {
 				crt_fingerprint="$(
 					"$EASYRSA_OPENSSL" x509 -in "$crt_source" \
 						-noout -sha256 -fingerprint
-					)" || die "build_self_sign - Failed -fingerprint"
+					)" || die "self_sign - Failed -fingerprint"
 				# strip prefix
 				crt_fingerprint="${crt_fingerprint#*=}"
 			fi
@@ -5536,13 +5536,13 @@ case "$cmd" in
 		verify_working_env
 		[ -z "$alias_days" ] || \
 			export EASYRSA_CERT_EXPIRE="$alias_days"
-		build_self_sign server "$@"
+		self_sign server "$@"
 		;;
 	self-sign-client)
 		verify_working_env
 		[ -z "$alias_days" ] || \
 			export EASYRSA_CERT_EXPIRE="$alias_days"
-		build_self_sign client "$@"
+		self_sign client "$@"
 		;;
 	gen-dh)
 		verify_working_env
