gen-crl: Replace file-move with file-copy-preserve-attribs
Using 'mksh/mv.exe' to move the temp-file to the target-file causes
an unnecessary confirmation prompt.

Using 'mksh/cp.exe' to copy (preserving attributes) the temp-file to
the target-file, no confirmation prompt is required.

Possibly, a bug is MKSH tools.

Signed-off-by: Richard T Bonhomme <tincantech@protonmail.com>

diff --git a/easyrsa3/easyrsa b/easyrsa3/easyrsa
--- a/easyrsa3/easyrsa
+++ b/easyrsa3/easyrsa
@@ -3546,11 +3546,7 @@ gen_crl() {
 			die "CRL Generation failed."
 
 	# Move temp-files to target-files
-	mv "$out_file_tmp" "$out_file" || mv_temp_error=1
-	if [ "$mv_temp_error" ]; then
-		#rm -f "$out_file"
-		die "Failed to move temp CRL file."
-	fi
+	cp -p "$out_file_tmp" "$out_file" || die "Failed to move temp CRL file."
 
 	# Copy to DER - As published by OpenSSL
 	if "$EASYRSA_OPENSSL" crl -in "$out_file" -out "$out_der" \
