renew: Replace 'up23_upgrade_ca' with 'ca_unique_subject_no'
These two do essentially the same:
* Make sure index.txt.attr file contains 'unique_subject = no'

Signed-off-by: Richard T Bonhomme <tincantech@protonmail.com>

diff --git a/easyrsa3/easyrsa b/easyrsa3/easyrsa
--- a/easyrsa3/easyrsa
+++ b/easyrsa3/easyrsa
@@ -2758,7 +2758,7 @@ Run easyrsa without commands for usage and command help."
 	inline_in="$in_dir/inline/${file_name_base}.inline"
 
 	# Upgrade CA index.txt.attr - unique_subject = no
-	up23_upgrade_ca || \
+	ca_unique_subject_no || \
 		die "Failed to upgrade CA to support renewal."
 
 	# deprecate ALL options
@@ -2986,6 +2986,29 @@ Failed to remove inline file:
 
 	return 0
 } # => renew_move()
+
+# Set unique_subject = no in index.txt.attr
+ca_unique_subject_no() {
+	[ -d "$EASYRSA_PKI" ] || return 0
+	attr_file="$EASYRSA_PKI/index.txt.attr"
+	verbose "\
+Confirm: index.txt.attr exists and 'unique_subject = no'"
+
+	if [ -f "$attr_file" ]; then
+		if grep -q '^[[:blank:]]*unique_subject = no' \
+			"$attr_file"
+		then
+			return 0
+		fi
+	else
+		return 0
+	fi
+
+	# Otherwise this is required for all easyrsa v3
+	printf '%s\n' 'unique_subject = no' > "$attr_file" || \
+		die "ca_unique_subject_no - Failed write"
+	verbose "Set unique_subject = no in index.txt.attr"
+} #=> ca_unique_subject_no()
 
 # revoke-renewed backend
 revoke_renewed() {
