Improve user messages and wrap long lines, no functional changes.
Signed-off-by: Richard T Bonhomme <tincantech@protonmail.com>

diff --git a/easyrsa3/easyrsa b/easyrsa3/easyrsa
--- a/easyrsa3/easyrsa
+++ b/easyrsa3/easyrsa
@@ -2,12 +2,13 @@
 
 # Easy-RSA 3 -- A Shell-based CA Utility
 #
-# Copyright (C) 2018 by the Open-Source OpenVPN development community.
+# Copyright (C) 2023 - The Open-Source OpenVPN development community.
 # A full list of contributors can be found on Github at:
 #   https://github.com/OpenVPN/easy-rsa/graphs/contributors
 #
-# This code released under version 2 of the GNU GPL; see COPYING and the
-# Licensing/ directory of this project for full licensing details.
+# This code released under version 2 of the GNU GPL; see COPYING
+# and the Licensing/ directory of this project for full licensing
+# details.
 
 # Help/usage output to stdout
 usage() {
@@ -163,7 +164,7 @@ cmd_help() {
       This request file must exist in the reqs/ dir and have a .req file
       extension. See import-req below for importing reqs from other sources."
 		opts="
-      * preserve - When signing a request, 'preserve' the DN-field order of the CSR."
+      * preserve - Use the DN-field order of the CSR not the CA."
 	;;
 	build|build-client-full|build-server-full|build-serverClient-full)
 		text="
@@ -401,8 +402,8 @@ cmd_help() {
 
       Upgrade <type> must be one of:
 
-      * pki - Upgrade EasyRSA v2.x PKI to EasyRSA v3.x PKI (includes CA below)
-      * ca  - Upgrade EasyRSA v3.0.5 CA or older to EasyRSA v3.0.6 CA or later."
+      * pki - Upgrade EasyRSA v2.x PKI to v3.x PKI (includes CA below)
+      * ca  - Upgrade EasyRSA v3.0.5 CA or older to v3.0.6 CA or later."
 	;;
 	altname|subjectaltname|san)
 		text_only=1
@@ -411,9 +412,9 @@ cmd_help() {
 
       This global option adds a subjectAltName to the request or issued
       certificate. It MUST be in a valid format accepted by openssl or
-      req/cert generation will fail. Note that including multiple such names
-      requires them to be comma-separated; further invocations of this
-      option will REPLACE the value.
+      req/cert generation will fail. Note that including multiple such
+      names requires them to be comma-separated; further invocations of
+      this option will REPLACE the value.
 
       Examples of the SAN_FORMAT_STRING shown below:
 
@@ -523,7 +524,7 @@ Certificate & Request options: (these impact cert/req field values)
 
 --no-text       : Create certificates without human readable text
 --days=#        : Sets the signing validity to the specified number of days
-                  Also applies to renewal period. For details, see: 'help days'
+                  Applies to other commands. For details, see: 'help days'
 --startdate=DATE: Sets the SSL option '-startdate' (Format 'YYYYMMDDhhmmssZ')
 --enddate=DATE  : Sets the SSL option '-enddate' (Format 'YYYYMMDDhhmmssZ')
 
@@ -641,7 +642,7 @@ $msg
 
 Type the word '$value' to continue, or any other input to abort."
 	printf %s "  $prompt"
-	# shellcheck disable=SC2162 # read without -r will mangle backslashes
+	# shellcheck disable=SC2162 # read without -r will mangle ..
 	read input
 	printf '\n'
 	[ "$input" = "$value" ] && return
@@ -769,9 +770,9 @@ easyrsa_mktemp: temp-file EXISTS: $want_tmp_file"
 					continue
 				else
 					# atomic:
-					[ "$easyrsa_host_os" = win ] && {
+					if [ "$easyrsa_host_os" = win ]; then
 						set -o noclobber
-					}
+					fi
 
 					if mv "$shotfile" "$want_tmp_file"; then
 						# Assign external temp-file name
@@ -779,9 +780,10 @@ easyrsa_mktemp: temp-file EXISTS: $want_tmp_file"
 						then
 							verbose "\
 easyrsa_mktemp: $1 temp-file OK: $want_tmp_file"
-							[ "$easyrsa_host_os" = win ] && {
+
+							if [ "$easyrsa_host_os" = win ]; then
 								set +o noclobber
-							}
+							fi
 							unset -v want_tmp_file shotfile
 							return
 						else
@@ -800,7 +802,6 @@ easyrsa_mktemp - failed for: $1 @ attempt=$i
 want_tmp_file: $want_tmp_file"
 	print "$err_msg" >> "$easyrsa_err_log"
 	die "$err_msg"
-
 } # => easyrsa_mktemp()
 
 # remove temp files and do terminal cleanups
@@ -1509,14 +1510,14 @@ install_data_to_pki: $context - Failed to install vars file"
 		: # ok
 	else
 		create_openssl_easyrsa_cnf > \
-			"${EASYRSA_PKI}/${ssl_cnf_file}" || \
-				die "install_data_to_pki - Missing: '$ssl_cnf_file'"
+			"${EASYRSA_PKI}/${ssl_cnf_file}" || die "\
+install_data_to_pki - Missing: '$ssl_cnf_file'"
 		verbose "\
 install_data_to_pki: $context - create_openssl_easyrsa_cnf OK"
 	fi
 
-	[ -d "$EASYRSA_EXT_DIR" ] || \
-		warn "install_data_to_pki - Missing: '$x509_types_dir'"
+	[ -d "$EASYRSA_EXT_DIR" ] || warn "\
+install_data_to_pki - Missing: '$x509_types_dir'"
 	verbose "install_data_to_pki: $context - COMPLETED"
 } # => install_data_to_pki ()
 
@@ -1829,7 +1830,8 @@ If you intended to start a new CA, run init-pki first."
 	if [ -f "$out_key" ]; then
 		user_error "\
 A CA private key exists but no ca.crt is found in your PKI:
-$EASYRSA_PKI
+* $EASYRSA_PKI
+
 Refusing to create a new CA as this would overwrite your
 current CA. To start a new CA, run init-pki first."
 	fi
@@ -2260,7 +2262,7 @@ Please update 'openssl-easyrsa.cnf' \
 to the latest Easy-RSA release."
 		fi
 
-		# Setup & insert the extra ext data keyed by a magic line
+		# Setup & insert the extra ext data keyed by magic line
 		extra_exts="
 req_extensions = req_extra
 [ req_extra ]
@@ -2340,6 +2342,7 @@ Your files are:
 * req: $req_out
 * key: $key_out${do_build_full:+ $NL}"
 
+	return 0
 } # => gen_req()
 
 # common signing backend
@@ -2805,23 +2808,27 @@ Run easyrsa without commands for usage and command help."
 
 	# referenced cert must exist:
 	[ -e "$crt_in" ] || user_error "\
-Unable to revoke as no certificate was found. Certificate was expected
-at: $crt_in"
+Unable to revoke as no certificate was found.
+Certificate was expected at:
+* $crt_in"
 
 	# Verify certificate
 	verify_file x509 "$crt_in" || user_error "\
-Unable to revoke as the input file is not a valid certificate. Unexpected
-input in file: $crt_in"
+Unable to revoke as the input-file is not a valid certificate.
+Certificate was expected at:
+* $crt_in"
 
 	# Verify request
 	if [ -e "$req_in" ]; then
 		verify_file req "$req_in" || user_error "\
 Unable to verify request. The file is not a valid request.
-Unexpected input in file: $req_in"
+Request was expected at:
+* $req_in"
 	fi
 
 	# get the serial number of the certificate
-	ssl_cert_serial "$crt_in" cert_serial
+	ssl_cert_serial "$crt_in" cert_serial || \
+		die "$cmd: Failed to get cert serial number!"
 
 	# Duplicate cert by serial file
 	dup_dir="$EASYRSA_PKI/certs_by_serial"
@@ -2833,9 +2840,9 @@ Unexpected input in file: $req_in"
 	key_out="$out_dir/private_by_serial/${cert_serial}.key"
 	req_out="$out_dir/reqs_by_serial/${cert_serial}.req"
 
-	# NEVER over-write a revoked cert, serial number must be unique
+	# NEVER over-write a revoked cert, serial must be unique
 	deny_msg="\
-Cannot revoke this certificate because a conflicting file exists.
+Cannot revoke this certificate, a conflicting file exists.
 *"
 	[ -e "$crt_out" ] && \
 		user_error "$deny_msg certificate: $crt_out"
@@ -2856,7 +2863,7 @@ Cannot revoke this certificate because a conflicting file exists.
 	warn "\
 This process is destructive!
 
-These files will be MOVED to the 'revoked' storage directory:
+These files will be MOVED to the 'revoked' sub-directory:
 * $crt_in${if_exist_key_in}${if_exist_req_in}
 
 These files will be DELETED:
@@ -2870,7 +2877,7 @@ The duplicate certificate:
 * $dup_crt_by_serial"
 
 	confirm "  Continue with revocation: " "yes" "\
-Please confirm you wish to revoke the certificate
+Please confirm that you wish to revoke the certificate
 with the following subject:
 
   $(display_dn x509 "$crt_in")
@@ -2891,10 +2898,11 @@ Failed to revoke certificate: revocation command failed."
 	revoke_move
 
 	notice "\
-                              * IMPORTANT *
+                        * IMPORTANT *
 
-Revocation was successful. You must run 'gen-crl' and upload a new CRL to your
-infrastructure in order to prevent the revoked certificate from being accepted."
+Revocation was successful. You must run 'gen-crl' and upload
+a new CRL to your infrastructure in order to prevent the revoked
+certificate from being accepted."
 
 	return 0
 } # => revoke()
@@ -3026,7 +3034,8 @@ Missing request file:
 	fi
 
 	# get the serial number of the certificate
-	ssl_cert_serial "$crt_in" cert_serial
+	ssl_cert_serial "$crt_in" cert_serial || \
+		die "$cmd: Failed to get cert serial number!"
 
 	# Duplicate cert by serial file
 	dup_dir="$EASYRSA_PKI/certs_by_serial"
@@ -3062,14 +3071,15 @@ Cannot renew this certificate, a conflicting file exists:
 		"TLS Web Server Authentication")
 			cert_type=server
 		;;
-	"TLS Web Server Authentication, TLS Web Client Authentication")
+		"TLS Web Server Auth"*", TLS Web Client Auth"*)
 			cert_type=serverClient
 		;;
 		*) die "Unknown key usage: $cert_ext_key_usage"
 	esac
 
 	# Use SAN from --san if set else use SAN from old cert
-	if echo "$EASYRSA_EXTRA_EXTS" | grep -q subjectAltName; then
+	if echo "$EASYRSA_EXTRA_EXTS" | grep -q subjectAltName
+	then
 		: # ok - Use current subjectAltName
 	else
 		san="$(
@@ -3087,7 +3097,7 @@ subjectAltName = $san"
 	warn "\
 This process is destructive!
 
-These files will be MOVED to 'renewed' storage directory:
+These files will be MOVED to the 'renewed' sub-directory:
 * $crt_in
 
 These files will be DELETED:
@@ -3127,7 +3137,8 @@ Renewal has failed to build a new certificate."
 
 	# inline it
 	# Over write existing because renew is successful
-	if inline_creds "$file_name_base" > "$inline_in"; then
+	if inline_creds "$file_name_base" > "$inline_in"
+	then
 		notice "\
 Inline file created:
 * $inline_in"
@@ -3141,12 +3152,13 @@ Failed to write inline file:
 	notice "\
 Renew was successful.
 
-                              * IMPORTANT *
+                          * IMPORTANT *
 
-Renew has created a new certificate, to replace the old certificate.
+Renew has created a new certificate, to replace the old one.
 
-To revoke the old certificate, once the new one has been deployed,
-use: 'revoke-renewed $file_name_base reason' ('reason' is optional)"
+To revoke the old certificate, once the new one has been
+deployed, use command:
+'revoke-renewed $file_name_base reason' ('reason' is optional)"
 
 	return 0
 } # => renew()
@@ -3272,22 +3284,26 @@ Run easyrsa without commands for usage and command help."
 	# referenced cert must exist:
 	[ -f "$crt_in" ] || user_error "\
 Unable to revoke as no renewed certificate was found.
-Certificate was expected at: $crt_in"
+Certificate was expected at:
+* $crt_in"
 
 	# Verify certificate
 	verify_file x509 "$crt_in" || user_error "\
-Unable to revoke as the input file is not a valid certificate. Unexpected
-input in file: $crt_in"
+Unable to revoke as the input-file is not a valid certificate.
+Certificate was expected at:
+* $crt_in"
 
 	# Verify request
 	if [ -e "$req_in" ]; then
 		verify_file req "$req_in" || user_error "\
 Unable to verify request. The file is not a valid request.
-Unexpected input in file: $req_in"
+Request was expected at:
+* $req_in"
 	fi
 
 	# get the serial number of the certificate
-	ssl_cert_serial "$crt_in" cert_serial
+	ssl_cert_serial "$crt_in" cert_serial || \
+		die "$cmd: Failed to get cert serial number!"
 
 	# Duplicate cert by serial file
 	dup_dir="$EASYRSA_PKI/certs_by_serial"
@@ -3299,9 +3315,9 @@ Unexpected input in file: $req_in"
 	key_out="$out_dir/private_by_serial/$cert_serial.key"
 	req_out="$out_dir/reqs_by_serial/$cert_serial.req"
 
-	# NEVER over-write a revoked cert, serial number must be unique
+	# NEVER over-write a revoked cert, serial must be unique
 	deny_msg="\
-Cannot revoke this certificate because a conflicting file exists.
+Cannot revoke this certificate, a conflicting file exists.
 *"
 	[ -e "$crt_out" ] && \
 		user_error "$deny_msg certificate: $crt_out"
@@ -3320,7 +3336,7 @@ Cannot revoke this certificate because a conflicting file exists.
 	warn "\
 This process is destructive!
 
-These files will be moved to the 'revoked' storage sub-directory:
+These files will be MOVED to the 'revoked' sub-directory:
 * $crt_in${if_exist_key_in}${if_exist_req_in}"
 
 	confirm "  Continue with revocation: " "yes" "\
@@ -3336,16 +3352,19 @@ These files will be moved to the 'revoked' storage sub-directory:
 	# Revoke the old (already renewed) certificate
 	easyrsa_openssl ca -utf8 -revoke "$crt_in" \
 		${crl_reason:+ -crl_reason "$crl_reason"} \
-		${EASYRSA_PASSIN:+ -passin "$EASYRSA_PASSIN"} \
-			|| die "Failed to revoke renewed certificate: revocation command failed."
+		${EASYRSA_PASSIN:+ -passin "$EASYRSA_PASSIN"} || \
+			die "\
+Failed to revoke renewed certificate: revocation command failed."
 
 	# move revoked files
 	revoke_renewed_move
 
-	notice "                              * IMPORTANT *
+	notice "\
+                      * IMPORTANT *
 
-Revocation was successful. You must run 'gen-crl' and upload a new CRL to your
-infrastructure in order to prevent the revoked certificate from being accepted."
+Revocation was successful. You must run 'gen-crl' and upload
+a new CRL to your infrastructure in order to prevent the revoked
+certificate from being accepted."
 
 	return 0
 } # => revoke_renewed()
@@ -3399,25 +3418,29 @@ Run easyrsa without commands for usage and command help."
 
 	# referenced cert must exist:
 	[ -f "$crt_in" ] || user_error "\
-Unable to rewind as no certificate was found. Certificate was expected
-at: $crt_in"
+Unable to rewind as no certificate was found.
+Certificate was expected at:
+* $crt_in"
 
 	# Verify certificate
 	verify_file x509 "$crt_in" || user_error "\
-Unable to rewind as the input file is not a valid certificate. Unexpected
-input in file: $crt_in"
+Unable to rewind as the input file is not a valid certificate.
+Certificate was expected at:
+* $crt_in"
 
 	# Verify request
 	if [ -e "$req_in" ]; then
 		verify_file req "$req_in" || user_error "\
 Unable to verify request. The file is not a valid request.
-Unexpected input in file: $req_in"
+Request was expected at:
+* $req_in"
 	fi
 
 	# get the commonName of the certificate via DN
 	crt_cn="$(
-		easyrsa_openssl x509 -in "$crt_in" -noout -subject -nameopt \
-		utf8,multiline | grep '^[[:blank:]]*commonName[[:blank:]]*= '
+		easyrsa_openssl x509 -in "$crt_in" -noout \
+		-subject -nameopt utf8,multiline | grep \
+			'^[[:blank:]]*commonName[[:blank:]]*=[[:blank:]]'
 		)" || die "Failed to find commonName in certificate"
 	crt_cn="${crt_cn#*= }"
 
@@ -3435,7 +3458,7 @@ Unexpected input in file: $req_in"
 
 	# NEVER over-write a renewed cert, revoke it first
 	deny_msg="\
-Cannot rewind this certificate because a conflicting file exists.
+Cannot rewind this certificate, a conflicting file exists.
 *"
 	[ -e "$crt_out" ] && \
 		user_error "$deny_msg certificate: $crt_out"
@@ -3448,7 +3471,7 @@ Cannot rewind this certificate because a conflicting file exists.
 	warn "\
 This process is destructive!
 
-These files will be moved to the NEW 'renewed' storage sub-directory:
+These files will be MOVED to the 'renewed' sub-directory:
 * $crt_in
 * $key_in
 * $req_in"
@@ -3533,23 +3556,27 @@ Run easyrsa without commands for usage and command help."
 
 	# referenced cert must exist:
 	[ -f "$crt_in" ] || user_error "\
-Unable to rebuild as no certificate was found. Certificate was expected
-at: $crt_in"
+Unable to rebuild as no certificate was found.
+Certificate was expected at:
+* $crt_in"
 
 	# Verify certificate
 	verify_file x509 "$crt_in" || user_error "\
-Unable to rebuild as the input file is not a valid certificate. Unexpected
-input in file: $crt_in"
+Unable to rebuild as the input file is not a valid certificate.
+Certificate was expected at:
+* $crt_in"
 
 	# Verify request
 	if [ -e "$req_in" ]; then
 		verify_file req "$req_in" || user_error "\
 Unable to verify request. The file is not a valid request.
-Unexpected input in file: $req_in"
+Request was expected at:
+* $req_in"
 	fi
 
 	# get the serial number of the certificate
-	ssl_cert_serial "$crt_in" cert_serial
+	ssl_cert_serial "$crt_in" cert_serial || \
+		die "$cmd: Failed to get cert serial number!"
 
 	# Duplicate cert by serial file
 	dup_dir="$EASYRSA_PKI/certs_by_serial"
@@ -3563,7 +3590,7 @@ Unexpected input in file: $req_in"
 
 	# NEVER over-write a renewed cert, revoke it first
 	deny_msg="\
-Cannot rebuild this certificate because a conflicting file exists.
+Cannot rebuild this certificate, a conflicting file exists.
 *"
 	[ -e "$crt_out" ] && \
 		user_error "$deny_msg certificate: $crt_out"
@@ -3586,14 +3613,16 @@ Cannot rebuild this certificate because a conflicting file exists.
 		"TLS Web Server Authentication")
 			cert_type=server
 			;;
-		"TLS Web Server Authentication, TLS Web Client Authentication")
+		"TLS Web Server Auth"*", TLS Web Client Auth"*)
 			cert_type=serverClient
 			;;
 		*) die "Unknown key usage: $cert_ext_key_usage"
 	esac
 
-	# Use SAN from --subject-alt-name if set else use SAN from old cert
-	if echo "$EASYRSA_EXTRA_EXTS" | grep -q subjectAltName; then
+	# Use SAN from --subject-alt-name, if set
+	# else use SAN from old cert
+	if echo "$EASYRSA_EXTRA_EXTS" | grep -q subjectAltName
+	then
 		: # ok - Use current subjectAltName
 	else
 		san="$(
@@ -3615,7 +3644,7 @@ subjectAltName = $san"
 	warn "\
 This process is destructive!
 
-These files will be moved to the 'renewed' storage directory:
+These files will be MOVED to the 'renewed' sub-directory:
 * $crt_in${if_exist_key_in}${if_exist_req_in}
 
 These files will be DELETED:
@@ -3643,7 +3672,8 @@ with the following subject:
 	error_undo_rebuild_move=1
 
 	# rebuild certificate
-	if EASYRSA_BATCH=1 build_full "$cert_type" "$file_name_base"; then
+	if EASYRSA_BATCH=1 build_full "$cert_type" "$file_name_base"
+	then
 		unset -v error_undo_rebuild_move
 	else
 		# If rebuild failed then restore cert, key and req. Otherwise,
@@ -3659,10 +3689,12 @@ Rebuild has failed to build a new certificate/key pair."
 
                               * IMPORTANT *
 
-Rebuild has created a new certificate and key, to replace both old files.
+Rebuild has created a new certificate and key, to replace
+both old files.
 
-To revoke the old certificate, once the new one has been deployed,
-use: 'revoke-renewed $file_name_base reason' ('reason' is optional)"
+To revoke the old certificate, once the new one has been
+deployed, use command:
+'revoke-renewed $file_name_base reason' ('reason' is optional)"
 
 	return 0
 } # => rebuild()
